#ifndef _INTERNAL_INPUT_H
#define _INTERNAL_INPUT_H

#define INTERNAL_INPUT_CLASS_NAME "internal-input"
#define INTERNAL_INPUT_NODES_PER_SOCKET 2

#define INTERNAL_INPUT_NODES_PER_SOCKET_PUBLIC_POOL 2

#endif